### ISSUE TITLE
1.4.0-post-1 version number is useless

### ISSUE THREAD

**Issue by alanbriolat** [ironfroggy/straight.plugin#18]
The [documentation](http://straightplugin.readthedocs.org/en/latest/getting-started.html) refers to `pip install straight.plugin` being the canonical method of installing `straight.plugin`, so I'm going to work on the assumption that it's intended for that method to work.  However, the latest version downloaded by that command (`1.4.0`) is broken, which you acknowledged and fixed in #9.  Unfortunately you chose a new version number (`1.4.0-post-1`) that ensured users will never get the working version with the supplied instructions, since it fails to parse as an accepted version number and gets counted as a "pre-release" ([according to `pip` documentation](https://pip.pypa.io/en/latest/reference/pip_install.html#pre-release-versions)).

_Please_ could you re-release that version under something sensible that won't leave loads of people downloading a broken version forever, especially since this project no longer seems to have any active development, and therefore may never have a `1.4.1` to eliminate this problem?  [PEP 440](https://www.python.org/dev/peps/pep-0440/) (and even it's predecessor [PEP 386](https://www.python.org/dev/peps/pep-0386)) suggests `1.4.0.post1` as more correct, but even `1.4.0-1`, to match your version numbering in the past, would work.

**Comment by pypingou** [comment]
Related to https://github.com/ironfroggy/straight.plugin/issues/17

**Comment by alanbriolat** [comment]
Looks like this issue and #17 are now fixed with the release of 1.4.1.
