### ISSUE TITLE
Imports are broken

### ISSUE THREAD

**Issue by joslinm** [ironfroggy/straight.plugin#9]
Your commit here has broken a fresh install from `pip install straight.plugin` :

> https://github.com/ironfroggy/straight.plugin/commit/46b9cb3b13d5e01366d0e7cb591e245e2b2a4fe4

$ python
Python 2.7.2+ (default, Oct  4 2011, 20:06:09) 
[GCC 4.6.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
from straight.plugin import load
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/straight/plugin/**init**.py", line 1, in <module>
    from straight.plugin import loaders
  File "/usr/local/lib/python2.7/dist-packages/straight/plugin/loaders.py", line 9, in <module>
    from straight.plugin.manager import PluginManager
ImportError: No module named manager

**Comment by mathturtle** [comment]
Also sorry to bump an old issue, but I am still getting this problem on my Ubuntu 14.04 laptop.  pip thinks that 1.4.0-post-1 is a prerelease for some reason.  Can you please change it to 1.4.0-1?

The solution for those later finding this page (it is pretty high on Google search results for the problem) is to run: `pip install --pre straight.plugin`

**Comment by pypingou** [comment]
See also: https://github.com/ironfroggy/straight.plugin/issues/17
